{% set name = "torchlie" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torchlie-{{ version }}.tar.gz
  sha256: 7874c4e8ed320b1850a1457260333d4972725627cf79efa04ae4d19259cc2e08

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pytorch

test:
  imports:
    - torchlie
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facebookresearch/theseus/torchlie
  summary: Torch extension for differentiable Lie groups.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
